# Generated by Django 5.1.2 on 2025-10-31 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_original_service'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_name_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='original_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_bookings', to='services.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.service'),
        ),
    ]
